apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-ext
spec:
  hosts:
  - redis.external.mesh.io # not used
  addresses:
  - 10.64.0.3
  ports:
  - number: 6379
    name: redis
    protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
  - address: 10.64.0.3
---
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: handler
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: 10.64.0.3:6379
    connectionPoolSize: 10
    quotas:
    - name: requestcount.quota.istio-system
      maxAmount: 1
      validDuration: 1s
      bucketDuration: 500ms
      rateLimitAlgorithm: ROLLING_WINDOW
      # The first matching override is applied.
      overrides:
      # The following override applies to 'grpctest' regardless of the source.
      - dimensions:
          destination: grpctest
          tenant: qa-long
          user: rphillips@zenoss.com
        maxAmount: 10
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    # If you specify/add a dimension, then the overrides *must* match all dimensions.
    destination: destination.labels["app"] | destination.service | "unknown"
    tenant: request.auth.claims["https://dev.zing.ninja/tenant"] | "unknown"
    user: request.auth.claims["https://dev.zing.ninja/email"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcount
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: grpctest
    namespace: default
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: handler.redisquota
    instances:
    - requestcount.quota
