apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: zing-jwt-validation
spec:
  targets:
  - name: grpctest
  origins:
  - jwt:
      issuer: "https://zenoss-dev.auth0.com/"
      jwksUri: "https://zenoss-dev.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN
